services:
  go-api-starter:
    image: go-api-starter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9876:9876
    user: root
    volumes:
      - ./:/app

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432