// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: availability.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAvailabilityById = `-- name: DeleteAvailabilityById :one
UPDATE availability
SET is_deleted = TRUE
WHERE id_availability = $1
RETURNING id_availability, inserted_at, updated_at, id_professional, init_datetime, end_datetime, init_hour, end_hour, type_availability, weekday_name, interval, resting, priority_entry, is_deleted, deleted_at
`

func (q *Queries) DeleteAvailabilityById(ctx context.Context, idAvailability int32) (Availability, error) {
	row := q.db.QueryRow(ctx, deleteAvailabilityById, idAvailability)
	var i Availability
	err := row.Scan(
		&i.IDAvailability,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.IDProfessional,
		&i.InitDatetime,
		&i.EndDatetime,
		&i.InitHour,
		&i.EndHour,
		&i.TypeAvailability,
		&i.WeekdayName,
		&i.Interval,
		&i.Resting,
		&i.PriorityEntry,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const insertAvailability = `-- name: InsertAvailability :one
INSERT INTO availability (
    id_professional,
    init_datetime,
    end_datetime,
    init_hour,
    end_hour,
    type_availability,
    weekday_name,
    interval,
    resting,
    priority_entry
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id_availability, inserted_at, updated_at, id_professional, init_datetime, end_datetime, init_hour, end_hour, type_availability, weekday_name, interval, resting, priority_entry, is_deleted, deleted_at
`

type InsertAvailabilityParams struct {
	IDProfessional   int32            `json:"id_professional"`
	InitDatetime     pgtype.Timestamp `json:"init_datetime"`
	EndDatetime      pgtype.Timestamp `json:"end_datetime"`
	InitHour         string           `json:"init_hour"`
	EndHour          string           `json:"end_hour"`
	TypeAvailability int32            `json:"type_availability"`
	WeekdayName      string           `json:"weekday_name"`
	Interval         int32            `json:"interval"`
	Resting          int32            `json:"resting"`
	PriorityEntry    int32            `json:"priority_entry"`
}

func (q *Queries) InsertAvailability(ctx context.Context, arg InsertAvailabilityParams) (Availability, error) {
	row := q.db.QueryRow(ctx, insertAvailability,
		arg.IDProfessional,
		arg.InitDatetime,
		arg.EndDatetime,
		arg.InitHour,
		arg.EndHour,
		arg.TypeAvailability,
		arg.WeekdayName,
		arg.Interval,
		arg.Resting,
		arg.PriorityEntry,
	)
	var i Availability
	err := row.Scan(
		&i.IDAvailability,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.IDProfessional,
		&i.InitDatetime,
		&i.EndDatetime,
		&i.InitHour,
		&i.EndHour,
		&i.TypeAvailability,
		&i.WeekdayName,
		&i.Interval,
		&i.Resting,
		&i.PriorityEntry,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const listAvailability = `-- name: ListAvailability :one
SELECT 
    id_availability,
    id_professional,
    init_datetime,
    end_datetime,
    init_hour,
    end_hour,
    type_availability,
    weekday_name,
    interval,
    priority_entry,
    is_deleted
FROM availability
WHERE id_availability = $1
`

type ListAvailabilityRow struct {
	IDAvailability   int32            `json:"id_availability"`
	IDProfessional   int32            `json:"id_professional"`
	InitDatetime     pgtype.Timestamp `json:"init_datetime"`
	EndDatetime      pgtype.Timestamp `json:"end_datetime"`
	InitHour         string           `json:"init_hour"`
	EndHour          string           `json:"end_hour"`
	TypeAvailability int32            `json:"type_availability"`
	WeekdayName      string           `json:"weekday_name"`
	Interval         int32            `json:"interval"`
	PriorityEntry    int32            `json:"priority_entry"`
	IsDeleted        bool             `json:"is_deleted"`
}

func (q *Queries) ListAvailability(ctx context.Context, idAvailability int32) (ListAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, listAvailability, idAvailability)
	var i ListAvailabilityRow
	err := row.Scan(
		&i.IDAvailability,
		&i.IDProfessional,
		&i.InitDatetime,
		&i.EndDatetime,
		&i.InitHour,
		&i.EndHour,
		&i.TypeAvailability,
		&i.WeekdayName,
		&i.Interval,
		&i.PriorityEntry,
		&i.IsDeleted,
	)
	return i, err
}

const listAvailabilityByProfessionalId = `-- name: ListAvailabilityByProfessionalId :many
SELECT
  id_availability,
  init_datetime,
  end_datetime,
  init_hour,
  end_hour,
  type_availability,
  weekday_name,
  interval,
  priority_entry,
  is_deleted
FROM availability
WHERE 1=1
  AND id_professional = $1
  AND CASE WHEN $2 = true THEN true ELSE is_deleted = false END
`

type ListAvailabilityByProfessionalIdParams struct {
	IDProfessional int32       `json:"id_professional"`
	Deleted        interface{} `json:"deleted"`
}

type ListAvailabilityByProfessionalIdRow struct {
	IDAvailability   int32            `json:"id_availability"`
	InitDatetime     pgtype.Timestamp `json:"init_datetime"`
	EndDatetime      pgtype.Timestamp `json:"end_datetime"`
	InitHour         string           `json:"init_hour"`
	EndHour          string           `json:"end_hour"`
	TypeAvailability int32            `json:"type_availability"`
	WeekdayName      string           `json:"weekday_name"`
	Interval         int32            `json:"interval"`
	PriorityEntry    int32            `json:"priority_entry"`
	IsDeleted        bool             `json:"is_deleted"`
}

func (q *Queries) ListAvailabilityByProfessionalId(ctx context.Context, arg ListAvailabilityByProfessionalIdParams) ([]ListAvailabilityByProfessionalIdRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByProfessionalId, arg.IDProfessional, arg.Deleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailabilityByProfessionalIdRow
	for rows.Next() {
		var i ListAvailabilityByProfessionalIdRow
		if err := rows.Scan(
			&i.IDAvailability,
			&i.InitDatetime,
			&i.EndDatetime,
			&i.InitHour,
			&i.EndHour,
			&i.TypeAvailability,
			&i.WeekdayName,
			&i.Interval,
			&i.PriorityEntry,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
