// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: blocker.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBlockerById = `-- name: DeleteBlockerById :one
UPDATE blocker
SET is_deleted = true
WHERE id_blocker = $1
RETURNING id_blocker, inserted_at, updated_at, title, description, id_professional, init_datetime, end_datetime, is_deleted, deleted_at
`

func (q *Queries) DeleteBlockerById(ctx context.Context, idBlocker int32) (Blocker, error) {
	row := q.db.QueryRow(ctx, deleteBlockerById, idBlocker)
	var i Blocker
	err := row.Scan(
		&i.IDBlocker,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.IDProfessional,
		&i.InitDatetime,
		&i.EndDatetime,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const getBlockerById = `-- name: GetBlockerById :one
SELECT
  id_blocker,
  id_professional,
  title,
  init_datetime,
  end_datetime,
  is_deleted
FROM blocker
WHERE 1=1
  AND id_blocker = $1
  AND CASE WHEN $2 = true THEN true ELSE is_deleted = false END
`

type GetBlockerByIdParams struct {
	IDBlocker int32       `json:"id_blocker"`
	Deleted   interface{} `json:"deleted"`
}

type GetBlockerByIdRow struct {
	IDBlocker      int32            `json:"id_blocker"`
	IDProfessional int32            `json:"id_professional"`
	Title          string           `json:"title"`
	InitDatetime   pgtype.Timestamp `json:"init_datetime"`
	EndDatetime    pgtype.Timestamp `json:"end_datetime"`
	IsDeleted      bool             `json:"is_deleted"`
}

func (q *Queries) GetBlockerById(ctx context.Context, arg GetBlockerByIdParams) (GetBlockerByIdRow, error) {
	row := q.db.QueryRow(ctx, getBlockerById, arg.IDBlocker, arg.Deleted)
	var i GetBlockerByIdRow
	err := row.Scan(
		&i.IDBlocker,
		&i.IDProfessional,
		&i.Title,
		&i.InitDatetime,
		&i.EndDatetime,
		&i.IsDeleted,
	)
	return i, err
}

const insertBlocker = `-- name: InsertBlocker :one
INSERT INTO blocker (
  id_professional,
  title,
  description,
  init_datetime,
  end_datetime
) VALUES (
  $1, 
  $2, 
  $3,
  $4,
  $5
)
RETURNING id_blocker, inserted_at, updated_at, title, description, id_professional, init_datetime, end_datetime, is_deleted, deleted_at
`

type InsertBlockerParams struct {
	IDProfessional int32            `json:"id_professional"`
	Title          string           `json:"title"`
	Description    pgtype.Text      `json:"description"`
	InitDatetime   pgtype.Timestamp `json:"init_datetime"`
	EndDatetime    pgtype.Timestamp `json:"end_datetime"`
}

func (q *Queries) InsertBlocker(ctx context.Context, arg InsertBlockerParams) (Blocker, error) {
	row := q.db.QueryRow(ctx, insertBlocker,
		arg.IDProfessional,
		arg.Title,
		arg.Description,
		arg.InitDatetime,
		arg.EndDatetime,
	)
	var i Blocker
	err := row.Scan(
		&i.IDBlocker,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.IDProfessional,
		&i.InitDatetime,
		&i.EndDatetime,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const listBlockerByProfessional = `-- name: ListBlockerByProfessional :many
SELECT
  id_blocker,
  id_professional,
  title,
  description,
  init_datetime,
  end_datetime,
  is_deleted
FROM blocker
WHERE 1=1
  AND id_professional = $1
  AND CASE WHEN $2 = true THEN true ELSE is_deleted = false END
`

type ListBlockerByProfessionalParams struct {
	IDProfessional int32       `json:"id_professional"`
	Deleted        interface{} `json:"deleted"`
}

type ListBlockerByProfessionalRow struct {
	IDBlocker      int32            `json:"id_blocker"`
	IDProfessional int32            `json:"id_professional"`
	Title          string           `json:"title"`
	Description    pgtype.Text      `json:"description"`
	InitDatetime   pgtype.Timestamp `json:"init_datetime"`
	EndDatetime    pgtype.Timestamp `json:"end_datetime"`
	IsDeleted      bool             `json:"is_deleted"`
}

func (q *Queries) ListBlockerByProfessional(ctx context.Context, arg ListBlockerByProfessionalParams) ([]ListBlockerByProfessionalRow, error) {
	rows, err := q.db.Query(ctx, listBlockerByProfessional, arg.IDProfessional, arg.Deleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockerByProfessionalRow
	for rows.Next() {
		var i ListBlockerByProfessionalRow
		if err := rows.Scan(
			&i.IDBlocker,
			&i.IDProfessional,
			&i.Title,
			&i.Description,
			&i.InitDatetime,
			&i.EndDatetime,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
