// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"database/sql"
	"time"
)

type Attribute struct {
	IDAttribute    int64  `json:"id_attribute"`
	IDProfessional int64  `json:"id_professional"`
	Attribute      string `json:"attribute"`
	Value          string `json:"value"`
}

type Availability struct {
	IDAvailability   int64     `json:"id_availability"`
	IDProfessional   int64     `json:"id_professional"`
	InitDatetime     time.Time `json:"init_datetime"`
	EndDatetime      time.Time `json:"end_datetime"`
	InitHour         string    `json:"init_hour"`
	EndHour          string    `json:"end_hour"`
	TypeAvailability int64     `json:"type_availability"`
	WeekdayName      string    `json:"weekday_name"`
	Interval         int64     `json:"interval"`
	Resting          int64     `json:"resting"`
	PriorityEntry    int64     `json:"priority_entry"`
	IsDeleted        int64     `json:"is_deleted"`
}

type Blocker struct {
	IDBlocker      int64          `json:"id_blocker"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	IDProfessional int64          `json:"id_professional"`
	InitDatetime   time.Time      `json:"init_datetime"`
	EndDatetime    time.Time      `json:"end_datetime"`
	IsDeleted      int64          `json:"is_deleted"`
}

type Professional struct {
	IDProfessional int64  `json:"id_professional"`
	ReferenceKey   string `json:"reference_key"`
	Especialidade  string `json:"especialidade"`
	Nome           string `json:"nome"`
}

type Slot struct {
	IDSlot         int64          `json:"id_slot"`
	InsertedAt     time.Time      `json:"inserted_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	IDAvailability sql.NullInt64  `json:"id_availability"`
	IDProfessional int64          `json:"id_professional"`
	Slot           time.Time      `json:"slot"`
	WeekdayName    string         `json:"weekday_name"`
	Interval       int64          `json:"interval"`
	PriorityEntry  int64          `json:"priority_entry"`
	StatusEntry    string         `json:"status_entry"`
	ExternalID     sql.NullString `json:"external_id"`
	Owner          sql.NullString `json:"owner"`
	IsDeleted      int64          `json:"is_deleted"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	IDBlocker      sql.NullInt64  `json:"id_blocker"`
}
