// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: professional.sql

package models

import (
	"context"
)

const checkProfessionalExists = `-- name: CheckProfessionalExists :one
SELECT 1
FROM professional
WHERE id_professional = $1
`

func (q *Queries) CheckProfessionalExists(ctx context.Context, idProfessional int32) (int32, error) {
	row := q.db.QueryRow(ctx, checkProfessionalExists, idProfessional)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getProfessionalInfo = `-- name: GetProfessionalInfo :one
SELECT
  id_professional,
  reference_key,
  nome,
  especialidade
FROM professional
WHERE reference_key = $1
`

type GetProfessionalInfoRow struct {
	IDProfessional int32  `json:"id_professional"`
	ReferenceKey   string `json:"reference_key"`
	Nome           string `json:"nome"`
	Especialidade  string `json:"especialidade"`
}

func (q *Queries) GetProfessionalInfo(ctx context.Context, referenceKey string) (GetProfessionalInfoRow, error) {
	row := q.db.QueryRow(ctx, getProfessionalInfo, referenceKey)
	var i GetProfessionalInfoRow
	err := row.Scan(
		&i.IDProfessional,
		&i.ReferenceKey,
		&i.Nome,
		&i.Especialidade,
	)
	return i, err
}

const insertAttribute = `-- name: InsertAttribute :one
INSERT INTO attribute (
  id_professional,
  attribute,
  value
) VALUES (
  $1,
  $2,
  $3
) RETURNING id_attribute, inserted_at, updated_at, id_professional, attribute, value
`

type InsertAttributeParams struct {
	IDProfessional int32  `json:"id_professional"`
	Attribute      string `json:"attribute"`
	Value          string `json:"value"`
}

func (q *Queries) InsertAttribute(ctx context.Context, arg InsertAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, insertAttribute, arg.IDProfessional, arg.Attribute, arg.Value)
	var i Attribute
	err := row.Scan(
		&i.IDAttribute,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.IDProfessional,
		&i.Attribute,
		&i.Value,
	)
	return i, err
}

const insertProfessional = `-- name: InsertProfessional :one
INSERT INTO professional (
  reference_key,
  nome,
  especialidade
) VALUES (
  $1, $2, $3
)
RETURNING id_professional, inserted_at, updated_at, reference_key, especialidade, nome
`

type InsertProfessionalParams struct {
	ReferenceKey  string `json:"reference_key"`
	Nome          string `json:"nome"`
	Especialidade string `json:"especialidade"`
}

func (q *Queries) InsertProfessional(ctx context.Context, arg InsertProfessionalParams) (Professional, error) {
	row := q.db.QueryRow(ctx, insertProfessional, arg.ReferenceKey, arg.Nome, arg.Especialidade)
	var i Professional
	err := row.Scan(
		&i.IDProfessional,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.ReferenceKey,
		&i.Especialidade,
		&i.Nome,
	)
	return i, err
}

const listAttributesByProfessionalId = `-- name: ListAttributesByProfessionalId :many
SELECT
  id_attribute,
  attribute,
  value
FROM attribute
WHERE id_professional = $1
`

type ListAttributesByProfessionalIdRow struct {
	IDAttribute int32  `json:"id_attribute"`
	Attribute   string `json:"attribute"`
	Value       string `json:"value"`
}

func (q *Queries) ListAttributesByProfessionalId(ctx context.Context, idProfessional int32) ([]ListAttributesByProfessionalIdRow, error) {
	rows, err := q.db.Query(ctx, listAttributesByProfessionalId, idProfessional)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttributesByProfessionalIdRow
	for rows.Next() {
		var i ListAttributesByProfessionalIdRow
		if err := rows.Scan(&i.IDAttribute, &i.Attribute, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
