// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: slot.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSlot = `-- name: CreateSlot :one
INSERT INTO slot(
  id_professional,
  id_availability,
  slot,
  weekday_name,
  interval,
  priority_entry,
  status_entry
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id_slot, inserted_at, updated_at, id_availability, id_professional, slot, weekday_name, interval, priority_entry, status_entry, id_external, owner, is_deleted, deleted_at, id_blocker
`

type CreateSlotParams struct {
	IDProfessional int32            `json:"id_professional"`
	IDAvailability pgtype.Int4      `json:"id_availability"`
	Slot           pgtype.Timestamp `json:"slot"`
	WeekdayName    string           `json:"weekday_name"`
	Interval       int32            `json:"interval"`
	PriorityEntry  int32            `json:"priority_entry"`
	StatusEntry    string           `json:"status_entry"`
}

func (q *Queries) CreateSlot(ctx context.Context, arg CreateSlotParams) (Slot, error) {
	row := q.db.QueryRow(ctx, createSlot,
		arg.IDProfessional,
		arg.IDAvailability,
		arg.Slot,
		arg.WeekdayName,
		arg.Interval,
		arg.PriorityEntry,
		arg.StatusEntry,
	)
	var i Slot
	err := row.Scan(
		&i.IDSlot,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.IDAvailability,
		&i.IDProfessional,
		&i.Slot,
		&i.WeekdayName,
		&i.Interval,
		&i.PriorityEntry,
		&i.StatusEntry,
		&i.IDExternal,
		&i.Owner,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.IDBlocker,
	)
	return i, err
}

const deleteSlotById = `-- name: DeleteSlotById :exec
UPDATE slot
SET is_deleted = TRUE,
  updated_at = CURRENT_TIMESTAMP,
  deleted_at = CURRENT_TIMESTAMP
WHERE id_slot = $1
`

func (q *Queries) DeleteSlotById(ctx context.Context, idSlot int32) error {
	_, err := q.db.Exec(ctx, deleteSlotById, idSlot)
	return err
}

const getExistingSlot = `-- name: GetExistingSlot :one
SELECT id_slot
FROM slot s
WHERE 1=1
  AND is_deleted = false
	AND id_professional = $1
	AND $2 between slot and slot + (INTERVAL '1 min' * (interval -1))
    AND priority_entry = $3
`

type GetExistingSlotParams struct {
	IDProfessional int32            `json:"id_professional"`
	Slot           pgtype.Timestamp `json:"slot"`
	PriorityEntry  int32            `json:"priority_entry"`
}

func (q *Queries) GetExistingSlot(ctx context.Context, arg GetExistingSlotParams) (int32, error) {
	row := q.db.QueryRow(ctx, getExistingSlot, arg.IDProfessional, arg.Slot, arg.PriorityEntry)
	var id_slot int32
	err := row.Scan(&id_slot)
	return id_slot, err
}

const getSlotById = `-- name: GetSlotById :one
SELECT
  id_slot,
  inserted_at,
  updated_at,
  id_professional,
  id_availability,
  slot,
  weekday_name,
  interval,
  priority_entry,
  status_entry,
  owner,
  id_external,
  is_deleted
FROM slot
WHERE 1=1
  AND id_slot = $1
  AND CASE WHEN $2 = true THEN true ELSE is_deleted = FALSE END
`

type GetSlotByIdParams struct {
	IDSlot  int32       `json:"id_slot"`
	Deleted interface{} `json:"deleted"`
}

type GetSlotByIdRow struct {
	IDSlot         int32            `json:"id_slot"`
	InsertedAt     pgtype.Timestamp `json:"inserted_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	IDProfessional int32            `json:"id_professional"`
	IDAvailability pgtype.Int4      `json:"id_availability"`
	Slot           pgtype.Timestamp `json:"slot"`
	WeekdayName    string           `json:"weekday_name"`
	Interval       int32            `json:"interval"`
	PriorityEntry  int32            `json:"priority_entry"`
	StatusEntry    string           `json:"status_entry"`
	Owner          pgtype.Text      `json:"owner"`
	IDExternal     pgtype.Text      `json:"id_external"`
	IsDeleted      bool             `json:"is_deleted"`
}

func (q *Queries) GetSlotById(ctx context.Context, arg GetSlotByIdParams) (GetSlotByIdRow, error) {
	row := q.db.QueryRow(ctx, getSlotById, arg.IDSlot, arg.Deleted)
	var i GetSlotByIdRow
	err := row.Scan(
		&i.IDSlot,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.IDProfessional,
		&i.IDAvailability,
		&i.Slot,
		&i.WeekdayName,
		&i.Interval,
		&i.PriorityEntry,
		&i.StatusEntry,
		&i.Owner,
		&i.IDExternal,
		&i.IsDeleted,
	)
	return i, err
}

const insertSlot = `-- name: InsertSlot :one
INSERT INTO slot (
    id_professional,
    id_availability,
    slot,
    weekday_name,
    interval,
    priority_entry,
    status_entry,
    id_blocker
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id_slot, slot
`

type InsertSlotParams struct {
	IDProfessional int32            `json:"id_professional"`
	IDAvailability pgtype.Int4      `json:"id_availability"`
	Slot           pgtype.Timestamp `json:"slot"`
	WeekdayName    string           `json:"weekday_name"`
	Interval       int32            `json:"interval"`
	PriorityEntry  int32            `json:"priority_entry"`
	StatusEntry    string           `json:"status_entry"`
	IDBlocker      pgtype.Int4      `json:"id_blocker"`
}

type InsertSlotRow struct {
	IDSlot int32            `json:"id_slot"`
	Slot   pgtype.Timestamp `json:"slot"`
}

func (q *Queries) InsertSlot(ctx context.Context, arg InsertSlotParams) (InsertSlotRow, error) {
	row := q.db.QueryRow(ctx, insertSlot,
		arg.IDProfessional,
		arg.IDAvailability,
		arg.Slot,
		arg.WeekdayName,
		arg.Interval,
		arg.PriorityEntry,
		arg.StatusEntry,
		arg.IDBlocker,
	)
	var i InsertSlotRow
	err := row.Scan(&i.IDSlot, &i.Slot)
	return i, err
}

const listSlots = `-- name: ListSlots :many
SELECT
  s.id_slot,
  s.status_entry,
  s.inserted_at,
  s.updated_at,
  p.reference_key,
  s.id_availability,
  s.slot,
  p.especialidade,
  s.weekday_name,
  s.interval,
  s.priority_entry,
  s.owner,
  s.id_external,
  s.is_deleted,
  s.deleted_at,
  s.id_blocker
FROM slot s
LEFT JOIN professional p on s.id_professional = p.id_professional
WHERE 1=1
  AND CASE WHEN $1 = true THEN true ELSE is_deleted = false END
  AND CASE WHEN $2 = true THEN cast(concat(extract(hour from slot), ':', extract(minute from slot)) as time) between cast($3::varchar as time) and cast($4::varchar as time) ELSE true END
  AND slot between $5 and $6
  AND CASE WHEN $7 = true THEN p.reference_key = ANY($8::varchar[]) ELSE true END
  AND CASE WHEN $9 = true THEN s.status_entry = 'open' ELSE true END
  AND CASE WHEN $10 = true THEN p.especialidade = ANY($11::varchar[]) ELSE true END
  AND CASE WHEN $12 = true THEN s.id_professional in (
    SELECT a.id_professional FROM attribute a WHERE attribute = 'idclinica' and value = ANY($13::varchar[])
  ) ELSE true END
ORDER BY s.slot
`

type ListSlotsParams struct {
	Deleted         interface{}      `json:"deleted"`
	IsHour          interface{}      `json:"is_hour"`
	InitHour        string           `json:"init_hour"`
	EndHour         string           `json:"end_hour"`
	SlotInit        pgtype.Timestamp `json:"slot_init"`
	SlotEnd         pgtype.Timestamp `json:"slot_end"`
	IsProfessional  interface{}      `json:"is_professional"`
	ReferenceKey    []string         `json:"reference_key"`
	IsOpen          interface{}      `json:"is_open"`
	IsEspecialidade interface{}      `json:"is_especialidade"`
	Especialidade   []string         `json:"especialidade"`
	IsIdclinica     interface{}      `json:"is_idclinica"`
	Idclinica       []string         `json:"idclinica"`
}

type ListSlotsRow struct {
	IDSlot         int32            `json:"id_slot"`
	StatusEntry    string           `json:"status_entry"`
	InsertedAt     pgtype.Timestamp `json:"inserted_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	ReferenceKey   pgtype.Text      `json:"reference_key"`
	IDAvailability pgtype.Int4      `json:"id_availability"`
	Slot           pgtype.Timestamp `json:"slot"`
	Especialidade  pgtype.Text      `json:"especialidade"`
	WeekdayName    string           `json:"weekday_name"`
	Interval       int32            `json:"interval"`
	PriorityEntry  int32            `json:"priority_entry"`
	Owner          pgtype.Text      `json:"owner"`
	IDExternal     pgtype.Text      `json:"id_external"`
	IsDeleted      bool             `json:"is_deleted"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	IDBlocker      pgtype.Int4      `json:"id_blocker"`
}

func (q *Queries) ListSlots(ctx context.Context, arg ListSlotsParams) ([]ListSlotsRow, error) {
	rows, err := q.db.Query(ctx, listSlots,
		arg.Deleted,
		arg.IsHour,
		arg.InitHour,
		arg.EndHour,
		arg.SlotInit,
		arg.SlotEnd,
		arg.IsProfessional,
		arg.ReferenceKey,
		arg.IsOpen,
		arg.IsEspecialidade,
		arg.Especialidade,
		arg.IsIdclinica,
		arg.Idclinica,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSlotsRow
	for rows.Next() {
		var i ListSlotsRow
		if err := rows.Scan(
			&i.IDSlot,
			&i.StatusEntry,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.ReferenceKey,
			&i.IDAvailability,
			&i.Slot,
			&i.Especialidade,
			&i.WeekdayName,
			&i.Interval,
			&i.PriorityEntry,
			&i.Owner,
			&i.IDExternal,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.IDBlocker,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsByIdAvailability = `-- name: ListSlotsByIdAvailability :many
SELECT
  id_slot
FROM slot
WHERE 1=1
  AND is_deleted = FALSE
  AND id_availability = $1
`

func (q *Queries) ListSlotsByIdAvailability(ctx context.Context, idAvailability pgtype.Int4) ([]int32, error) {
	rows, err := q.db.Query(ctx, listSlotsByIdAvailability, idAvailability)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id_slot int32
		if err := rows.Scan(&id_slot); err != nil {
			return nil, err
		}
		items = append(items, id_slot)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsSummary = `-- name: ListSlotsSummary :many
SELECT
  date_trunc($1::varchar, s.slot)::timestamp as timeref,
	s.status_entry,
	count(*) as counting
FROM slot s
LEFT JOIN professional p on s.id_professional = p.id_professional
WHERE 1=1
  AND CASE WHEN $2 = true THEN true ELSE is_deleted = false END
  AND CASE WHEN $3 = true THEN cast(concat(extract(hour from slot), ':', extract(minute from slot)) as time) between cast($4::varchar as time) and cast($5::varchar as time) ELSE true END
  AND slot between $6 and $7
  AND CASE WHEN $8 = true THEN p.reference_key = ANY($9::varchar[]) ELSE true END
  AND CASE WHEN $10 = true THEN s.status_entry = 'open' ELSE true END
  AND CASE WHEN $11 = true THEN p.especialidade = ANY($12::varchar[]) ELSE true END
  AND CASE WHEN $13 = true THEN s.id_professional in (
    SELECT a.id_professional FROM attribute a WHERE attribute = 'idclinica' and value = ANY($14::varchar[])
  ) ELSE true END
GROUP BY 1,2
ORDER BY 1,2
`

type ListSlotsSummaryParams struct {
	Timing          string           `json:"timing"`
	Deleted         interface{}      `json:"deleted"`
	IsHour          interface{}      `json:"is_hour"`
	InitHour        string           `json:"init_hour"`
	EndHour         string           `json:"end_hour"`
	SlotInit        pgtype.Timestamp `json:"slot_init"`
	SlotEnd         pgtype.Timestamp `json:"slot_end"`
	IsProfessional  interface{}      `json:"is_professional"`
	ReferenceKey    []string         `json:"reference_key"`
	IsOpen          interface{}      `json:"is_open"`
	IsEspecialidade interface{}      `json:"is_especialidade"`
	Especialidade   []string         `json:"especialidade"`
	IsIdclinica     interface{}      `json:"is_idclinica"`
	Idclinica       []string         `json:"idclinica"`
}

type ListSlotsSummaryRow struct {
	Timeref     pgtype.Timestamp `json:"timeref"`
	StatusEntry string           `json:"status_entry"`
	Counting    int64            `json:"counting"`
}

func (q *Queries) ListSlotsSummary(ctx context.Context, arg ListSlotsSummaryParams) ([]ListSlotsSummaryRow, error) {
	rows, err := q.db.Query(ctx, listSlotsSummary,
		arg.Timing,
		arg.Deleted,
		arg.IsHour,
		arg.InitHour,
		arg.EndHour,
		arg.SlotInit,
		arg.SlotEnd,
		arg.IsProfessional,
		arg.ReferenceKey,
		arg.IsOpen,
		arg.IsEspecialidade,
		arg.Especialidade,
		arg.IsIdclinica,
		arg.Idclinica,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSlotsSummaryRow
	for rows.Next() {
		var i ListSlotsSummaryRow
		if err := rows.Scan(&i.Timeref, &i.StatusEntry, &i.Counting); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSlot = `-- name: UpdateSlot :one
UPDATE slot
SET status_entry = $1,
    priority_entry = $2,
    owner = $3,
    id_external = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id_slot = $5
RETURNING id_slot, inserted_at, updated_at, id_availability, id_professional, slot, weekday_name, interval, priority_entry, status_entry, id_external, owner, is_deleted, deleted_at, id_blocker
`

type UpdateSlotParams struct {
	StatusEntry   string      `json:"status_entry"`
	PriorityEntry int32       `json:"priority_entry"`
	Owner         pgtype.Text `json:"owner"`
	IDExternal    pgtype.Text `json:"id_external"`
	IDSlot        int32       `json:"id_slot"`
}

func (q *Queries) UpdateSlot(ctx context.Context, arg UpdateSlotParams) (Slot, error) {
	row := q.db.QueryRow(ctx, updateSlot,
		arg.StatusEntry,
		arg.PriorityEntry,
		arg.Owner,
		arg.IDExternal,
		arg.IDSlot,
	)
	var i Slot
	err := row.Scan(
		&i.IDSlot,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.IDAvailability,
		&i.IDProfessional,
		&i.Slot,
		&i.WeekdayName,
		&i.Interval,
		&i.PriorityEntry,
		&i.StatusEntry,
		&i.IDExternal,
		&i.Owner,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.IDBlocker,
	)
	return i, err
}

const updateSlotSetBlocker = `-- name: UpdateSlotSetBlocker :many
UPDATE slot
SET status_entry = $1,
	  id_blocker = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE 1=1
	AND id_professional = $3
  AND slot >= $4 AND slot <= $5
RETURNING id_slot, inserted_at, updated_at, id_availability, id_professional, slot, weekday_name, interval, priority_entry, status_entry, id_external, owner, is_deleted, deleted_at, id_blocker
`

type UpdateSlotSetBlockerParams struct {
	StatusEntry    string           `json:"status_entry"`
	IDBlocker      pgtype.Int4      `json:"id_blocker"`
	IDProfessional int32            `json:"id_professional"`
	InitBlocker    pgtype.Timestamp `json:"init_blocker"`
	EndBlocker     pgtype.Timestamp `json:"end_blocker"`
}

func (q *Queries) UpdateSlotSetBlocker(ctx context.Context, arg UpdateSlotSetBlockerParams) ([]Slot, error) {
	rows, err := q.db.Query(ctx, updateSlotSetBlocker,
		arg.StatusEntry,
		arg.IDBlocker,
		arg.IDProfessional,
		arg.InitBlocker,
		arg.EndBlocker,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Slot
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.IDSlot,
			&i.InsertedAt,
			&i.UpdatedAt,
			&i.IDAvailability,
			&i.IDProfessional,
			&i.Slot,
			&i.WeekdayName,
			&i.Interval,
			&i.PriorityEntry,
			&i.StatusEntry,
			&i.IDExternal,
			&i.Owner,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.IDBlocker,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
